.flake8
.github/workflows/python-app.yml
repobee_sanitizer/__init__.py
repobee_sanitizer/sanitizer.py
setup.py
tests/test_file_sanitizer.py

[test] Setup CI with GitHub Actions

---

.github/workflows/python-app.yml
setup.py

[test] Setup Codecov integration

---

.github/workflows/python-app.yml
repobee_sanitizer/_sanitize_file.py

Just trying to get Codecov to post on pull requests...
#10

[misc] Use XML report for Codecov

---

README.md

Add draft for readme documentation

---

tests/conftest.py
tests/helpers/testhelpers.py
tests/test_file_sanitizer.py

[test] Extract helper functions into separate module

---

repobee_sanitizer/_sanitize_repo.py
tests/test_ext_commands.py

Make sanitize repo return FAILURE when there are uncommited staged files

---

repobee_sanitizer/_sanitize_repo.py
tests/test_ext_commands.py

Dont allow untracked or unstaged files in commit

---

tests/test_ext_commands.py

Fix #37  
Now the only problem is that since we closed the other PRs we haven't closed any of their previous issues (#33 and #37)

[test] Fix staged and unstaged string matching in test

---

tests/test_ext_commands.py

[test] Test that sanitize repo raises error when file list does not exist

---

README.md

Also improved formatting
Fix #46

[docs] Add README syntax highlighting

---

LICENSE
repobee_sanitizer/_sanitize.py
repobee_sanitizer/sanitizer.py
setup.py

Removed author from all modules and updated setup.py and LICENSE with all authors.
Fix #27

[docs] Fix authorship

---

.github/workflows/python-app.yml
requirements/dev.txt

[test] Add black --check to CI

---

repobee_sanitizer/_sanitize_repo.py
tests/test_ext_commands.py

[fix] Change discover_dirty_files to return relative paths

---

repobee_sanitizer/_sanitize_file.py
repobee_sanitizer/_sanitize_repo.py
requirements/app.txt
setup.py
tests/test_ext_commands.py

This includes changed the return values of callback functions to not return a Mapping
Fix #72

[feat] Update to support Repobee alpha 2

---

repobee_sanitizer/_sanitize_repo.py
tests/test_ext_commands.py

[feat] Remove file list mode

---

repobee_sanitizer/_syntax.py

[fix] Reset prefix after end of block

---

tests/test_ext_commands.py

[test] Add ISO8859 test

---

repobee_sanitizer/_sanitize_repo.py

Tell the user they can use --force with uncommited changes in repo 

---

repobee_sanitizer/_sanitize_repo.py
repobee_sanitizer/sanitizer.py
tests/test_ext_commands.py

[fix] Fix crash when no diff between old and new target-branch

---

repobee_sanitizer/sanitizer.py
requirements/app.txt
setup.py

[break] Update to Repobee 3.0 beta

---

repobee_sanitizer/_sanitize_repo.py
repobee_sanitizer/sanitizer.py
requirements/app.txt
setup.py

[fix] Update requirements to >= 3.0.0

---

repobee_sanitizer/_sanitize_repo.py

[fix] Update commit message

---

README.md

[docs] Include usage instructions in README

---

README.md

[docs] fix shred marker in README

---

repobee_sanitizer/_sanitize_repo.py
repobee_sanitizer/sanitizer.py
tests/test_ext_commands.py

[feat] Make commit message configurable

---

repobee_sanitizer/_sanitize_repo.py
repobee_sanitizer/sanitizer.py
setup.py

`python-black` decided to format some old code in a different way, which showed up in two PRs, this pr is to resolve that

Run autoformating

---

README.md
repobee_sanitizer/_gitutils.py
repobee_sanitizer/_sanitize_repo.py
repobee_sanitizer/sanitizer.py
setup.py
tests/test_ext_commands.py

A first draft
Fix #121 
@slarse we think we have the pr branch part working, however, the test to check that the target_branch is not modified seems to fail, the added file that we look for goes missing, perhaps we did something wrong, or just how we read the file in the test. Will keep looking at it but if you find something wrong whenever you have time to look at this that would be great

[feat] Add pull request workflow
